//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizzaHouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductPhotos = new HashSet<ProductPhotos>();
        }
    
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public int CategoriesId { get; set; }
        public decimal Price { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhotos> ProductPhotos { get; set; }
        public virtual Сategories Сategories { get; set; }
    }
}
